# Generated by Django 3.1.5 on 2022-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pesel_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesel',
            name='valid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
