# Generated by Django 3.1.5 on 2022-03-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220304_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('wartosc_samopoczucia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActualMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moods')),
            ],
        ),
    ]
