# Generated by Django 3.1.5 on 2022-03-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actualmood_moods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualmood',
            name='mood',
        ),
        migrations.AddField(
            model_name='actualmood',
            name='nazwa',
            field=models.CharField(default='e', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualmood',
            name='wartosc_samopoczucia',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
